Fix market exception:
java.lang.RuntimeException: Unable to stop service com.googlecode.gtalksms.MainService@40d7c380: java.lang.IllegalArgumentException: Receiver not registered: com.googlecode.gtalksms.receivers.PublicIntentReceiver@40d78628
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.googlecode.gtalksms.receivers.PublicIntentReceiver@40d78628
...
at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:354)
at com.googlecode.gtalksms.receivers.PublicIntentReceiver.onServiceStop(PublicIntentReceiver.java:56)
at com.googlecode.gtalksms.MainService.onDestroy(MainService.java:420)
at android.app.ActivityThread.handleStopService(ActivityThread.java:2512)